version: '2'
services:
  mongo:
    image: mongo:latest

  redis:
    image: redis:latest

  konfetka:
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo/konfetka
      - REDIS_URI=redis://redis
      - COOKIE_KEY=thecookiekeyissecret