version: '3'
services:
  mongo:
    image: mongo:latest

  redis:
    image: redis:latest

  konfetka:
    build: .
    restart: always
    ports:
      - 5001:5000
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo/konfetka
      - REDIS_URI=redis://redis
    volumes:
      - /usr/src/app/server/uploads
    labels:
      traefik.backend: "konfetka-prod"
      traefik.docker.network: "web"
      traefik.frontend.rule: "Host:dev.slavadev.com"
      traefik.enable: "true"
      traefik.port: "5000"
networks:
  web:
    external: true